#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Dec 12 16:59:36 CST 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=Visual-Vibrance-v0.3.2a.zip
